server:
  port:

spring:
  profiles:
    default: dev

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate.ddl-auto:
    open-in-view:
    show-sql:
    properties:
      hibernate.format_sql:
      hibernate.default_batch_fetch_size:

  ### OAuth2 Config
  security:
    oauth2.client:
      registration:
        google:
          clientId:
          clientSecret:
          scope:
        kakao:
          clientId:
          clientSecret:
          clientAuthenticationMethod:
          authorizationGrantType:
          redirectUri:
          scope:
          clientName:
      # Provider 설정
      provider:
        kakao:
          authorizationUri:
          tokenUri:
          userInfoUri:
          userNameAttribute:

app:
  ### OAuth Config
  oauth2:
    authorizedRedirectUris:
    cookie-max-age:

  ### JWT Config
  jwt:
    secret:
      access-token-secret-key:
      refresh-token-secret-key:
    expiry:
      access-token-expiry:
      refresh-token-expiry:

  ### Cookie Config
  cookie:
    oauth2-authorization-request-cookie-name:
    redirect-uri-param-cookie-name:
    refresh-token-cookie-name:
    cookie-expire-seconds:

  ### Image Config
  image:
    default-user-profile-image-url: